-- DROP SEQUENCE PRODUCAO.SEQ_GCORP_CIQ_TRABALHO;
CREATE SEQUENCE PRODUCAO.SEQ_AGENDAMEDICA_USERS
START WITH 1
MAXVALUE 999999999999999999999999999
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER;

-- DROP TABLE PRODUCAO.TAB_id CASCADE CONSTRAINTS;
CREATE TABLE PRODUCAO.TAB_AGENDAMEDICA_USERS
  (
  id        INTEGER NOT NULL,
  email     VARCHAR2(255) NOT NULL,
  name      VARCHAR2(255) NOT NULL,
  password  VARCHAR2(255) NOT NULL,
  username  VARCHAR2(255) NOT NULL,
  medic     NUMBER   DEFAULT 0 NOT NULL
  )
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
  PCTUSED    0
  PCTFREE    10
  INITRANS   1
  MAXTRANS   255
  STORAGE    (
INITIAL          64K
NEXT             1M
MAXSIZE          UNLIMITED
MINEXTENTS       1
MAXEXTENTS       UNLIMITED
PCTINCREASE      0
BUFFER_POOL      DEFAULT
FLASH_CACHE      DEFAULT
CELL_FLASH_CACHE DEFAULT
)
  LOGGING
  NOCOMPRESS
  NOCACHE
  NOPARALLEL
  MONITORING;

COMMENT ON COLUMN PRODUCAO.TAB_AGENDAMEDICA_USERS.id IS 'CODIGO INCREMENTAL';
COMMENT ON COLUMN PRODUCAO.TAB_AGENDAMEDICA_USERS.email IS 'EMAIL DO USUARIO TAMBEM USADO PARA LOGIN, CASO O USERNAME NÃO EXISTA';
COMMENT ON COLUMN PRODUCAO.TAB_AGENDAMEDICA_USERS.password IS 'SENHA DO USUARIO';
COMMENT ON COLUMN PRODUCAO.TAB_AGENDAMEDICA_USERS.username IS 'NOME DE USUARIO';
COMMENT ON COLUMN PRODUCAO.TAB_AGENDAMEDICA_USERS.medic IS 'SE 1, MEDICO, SE 2 NÃO MEDICO';

CREATE OR REPLACE TRIGGER PRODUCAO.TRG_AGENDAMEDICA_USERS BEFORE INSERT ON PRODUCAO.TAB_AGENDAMEDICA_USERS FOR EACH ROW
BEGIN
  IF (:NEW.id IS NULL) THEN
  SELECT SEQ_AGENDAMEDICA_USERS.nextval INTO :NEW.id FROM DUAL;
END IF;
END;
/
